import json

palette = {
    '.': 0, # transparent
    'b': 1, # blue (1E90FF)
    'f': 2, # face (FFDBAC)
    'x': 3, # black
    'r': 4, # red
    'y': 5, # yellow
    'w': 6, # white
    'd': 7, # dark blue
}

# We will define a 32x32 down frame 1
# This is a large ascii art block!
d1 = """
.........bbbbbbbbbbbbbb.........
.......bbbbbbbbbbbbbbbbbb.......
......bbbbbbbbbbbbbbbbbbbb......
.....bbbbbbbbbbwbbbbbbbbbbb.....
....bbbbbbbbbbbwwbbbbbbbbbbb....
...bbbbbbbyyyybbbbbyyyybbbbbb...
...bbbbbbyyyyybbbbbyyyyybbbbb...
..bbbbbbyyyyyybbbbbyyyyyybbbbb..
..bbbbbbbyyyybbbbbbbyyyybbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbyyyyyyyyyyyyyyyyyyybbbb..
..bbbbyyyyyyyyyyyyyyyyyyyyybbb..
..bbbyyyffffffffffffffffyyybbb..
..bbyyyffffffffffffffffffyyybb..
..bbyyfffffffxffffxfffffffyybb..
..bbyyffffffxxffffxxffffffyybb..
..bbyyffffffxxffffxxffffffyybb..
..bbyyfffffffxffffxfffffffyybb..
..bbyyffffffffffffffffffffyybb..
..bbbyyffffffffffffffffffyybbb..
..bbbbyyyyyyyyyyyyyyyyyyyyybbb..
...bbbbyyyyyyyyyyyyyyyyyyybbb...
...ddddbbbbbbbbbbbbbbbbbbdddd...
..rrddddbbbbbbbbbbbbbbbbddddrr..
.rrrrddddbbbbbbbbbbbbbbddddrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
..rrrrr..ddbbbbbbbbbbdd..rrrrr..
...rrr...ddbbbbbbbbbbdd...rrr...
.........dd..bbbb..dd...........
........rrrr......rrrr..........
.......rrrrrr....rrrrrr.........
"""
# That was 32 lines. Let's make sure it's 32 chars wide.
# Line 1: 9 dots, 14 b, 9 dots = 32.
# This looks great. Let's make d2 (walking down).

d2 = """
.........bbbbbbbbbbbbbb.........
.......bbbbbbbbbbbbbbbbbb.......
......bbbbbbbbbbbbbbbbbbbb......
.....bbbbbbbbbbwbbbbbbbbbbb.....
....bbbbbbbbbbbwwbbbbbbbbbbb....
...bbbbbbbyyyybbbbbyyyybbbbbb...
...bbbbbbyyyyybbbbbyyyyybbbbb...
..bbbbbbyyyyyybbbbbyyyyyybbbbb..
..bbbbbbbyyyybbbbbbbyyyybbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbyyyyyyyyyyyyyyyyyyybbbb..
..bbbbyyyyyyyyyyyyyyyyyyyyybbb..
..bbbyyyffffffffffffffffyyybbb..
..bbyyyffffffffffffffffffyyybb..
..bbyyfffffffxffffxfffffffyybb..
..bbyyffffffxxffffxxffffffyybb..
..bbyyffffffxxffffxxffffffyybb..
..bbyyfffffffxffffxfffffffyybb..
..bbyyffffffffffffffffffffyybb..
..bbbyyffffffffffffffffffyybbb..
..bbbbyyyyyyyyyyyyyyyyyyyyybbb..
...bbbbyyyyyyyyyyyyyyyyyyybbb...
...ddddbbbbbbbbbbbbbbbbbbdddd...
..rrddddbbbbbbbbbbbbbbbbddddrr..
.rrrrddddbbbbbbbbbbbbbbddddrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
..rrrrr..ddbbbbbbbbbbdd..rrrrr..
...rrr...ddbbbbbbbbbbdd...rrr...
.........dd..bbbb..dd...........
........rrrr.dddd...............
.......rrrrrr.dddd..............
"""

# Up 1
u1 = """
.........bbbbbbbbbbbbbb.........
.......bbbbbbbbbbbbbbbbbb.......
......bbbbbbbbbbbbbbbbbbbb......
.....bbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbb....
...bbbbbbbbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbbbbbbbb...
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
...bbbbbbbbbbbbbbbbbbbbbbbbbb...
...ddddbbbbbbbbbbbbbbbbbbdddd...
..rrddddbbbbbbbbbbbbbbbbddddrr..
.rrrrddddbbbbbbbbbbbbbbddddrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
..rrrrr..ddbbbbbbbbbbdd..rrrrr..
...rrr...ddbbbbbbbbbbdd...rrr...
.........dd..bbbb..dd...........
........rrrr......rrrr..........
.......rrrrrr....rrrrrr.........
"""

u2 = """
.........bbbbbbbbbbbbbb.........
.......bbbbbbbbbbbbbbbbbb.......
......bbbbbbbbbbbbbbbbbbbb......
.....bbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbb....
...bbbbbbbbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbbbbbbbb...
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
..bbbbbbbbbbbbbbbbbbbbbbbbbbbb..
...bbbbbbbbbbbbbbbbbbbbbbbbbb...
...ddddbbbbbbbbbbbbbbbbbbdddd...
..rrddddbbbbbbbbbbbbbbbbddddrr..
.rrrrddddbbbbbbbbbbbbbbddddrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
.rrrrrrddbbbbbbbbbbbbbbddrrrrrr.
..rrrrr..ddbbbbbbbbbbdd..rrrrr..
...rrr...ddbbbbbbbbbbdd...rrr...
.........dd..bbbb..dd...........
.............dddd.rrrr..........
............dddd.rrrrrr.........
"""

l1 = """
...........bbbbbbbbbbbb.........
.........bbbbbbbbbbbbbbbb.......
........bbbbbbbbbbbbbbbbbb......
.......bbbbbbbbbbyyyyybbbbb.....
......bbbbbbbbbyyyyyyyybbbbb....
.....bbbbbbbbbyyyyyyyyyybbbbb...
.....bbbbbbbbyyyffffyyyybbbbb...
....bbbbbbbbyyyfffffffyyybbbbb..
....bbbbbbbbyyfffffffffyybbbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbyyfffffffxfffyybbbb..
....bbbbbbbyyffffffxxfffyybbbb..
....bbbbbbbyyffffffxxfffyybbbb..
....bbbbbbbyyfffffffxfffyybbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbbyyfffffffffyybbbbb..
....bbbbbbbbyyyfffffffyyybbbbb..
.....bbbbbbbbyyyffffyyyybbbbb...
.....bbbbbbbbbyyyyyyyyyybbbbb...
......bbbbbbbbbyyyyyyyybbbbb....
......rrrrrbbbbbbyyyyybbbbb.....
.....rrrrrrrbbbbbbbbbbbbbb......
....rrrrrrrrrbbbbbbbbbbbb.......
....rrrrrrrrrrddbbbbbbdd........
....rrrrrrrrrrddbbbbbbdd........
.....rrrrrrrr.ddbbbbbbdd........
......rrrrrr..ddbbbbbbdd........
........rr....dd..bb..dd........
.............rrrr....rrrr.......
............rrrrrr..rrrrrr......
"""
# Let's make l2 same as l1 but feet moving
l2 = """
...........bbbbbbbbbbbb.........
.........bbbbbbbbbbbbbbbb.......
........bbbbbbbbbbbbbbbbbb......
.......bbbbbbbbbbyyyyybbbbb.....
......bbbbbbbbbyyyyyyyybbbbb....
.....bbbbbbbbbyyyyyyyyyybbbbb...
.....bbbbbbbbyyyffffyyyybbbbb...
....bbbbbbbbyyyfffffffyyybbbbb..
....bbbbbbbbyyfffffffffyybbbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbyyfffffffxfffyybbbb..
....bbbbbbbyyffffffxxfffyybbbb..
....bbbbbbbyyffffffxxfffyybbbb..
....bbbbbbbyyfffffffxfffyybbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbyyfffffffffffyybbbb..
....bbbbbbbbyyfffffffffyybbbbb..
....bbbbbbbbyyyfffffffyyybbbbb..
.....bbbbbbbbyyyffffyyyybbbbb...
.....bbbbbbbbbyyyyyyyyyybbbbb...
......bbbbbbbbbyyyyyyyybbbbb....
......rrrrrbbbbbbyyyyybbbbb.....
.....rrrrrrrbbbbbbbbbbbbbb......
....rrrrrrrrrbbbbbbbbbbbb.......
....rrrrrrrrrrddbbbbbbdd........
....rrrrrrrrrrddbbbbbbdd........
.....rrrrrrrr.ddbbbbbbdd........
......rrrrrr..ddbbbbbbdd........
........rr....dd..bb..dd........
.............rrrr...............
............rrrrrr..............
"""

# right is mirror of left
def mirror(s):
    lines = s.strip().split('\n')
    mirrored = []
    for line in lines:
        if len(line) < 32:
            line = line.ljust(32, '.')
        mirrored.append(line[::-1])
    return '\n'.join(mirrored)

r1 = mirror(l1)
r2 = mirror(l2)

def parse(art):
    lines = art.strip().split('\n')
    grid = []
    for line in lines:
        if len(line) < 32:
            line = line.ljust(32, '.')
        grid.append([palette.get(char, 0) for char in line])
    return grid

output = f"""const PLAYER_SPRITES = {{
  down: [
    {{
      pattern: {json.dumps(parse(d1))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }},
    {{
      pattern: {json.dumps(parse(d2))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }}
  ],
  up: [
    {{
      pattern: {json.dumps(parse(u1))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }},
    {{
      pattern: {json.dumps(parse(u2))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }}
  ],
  left: [
    {{
      pattern: {json.dumps(parse(l1))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }},
    {{
      pattern: {json.dumps(parse(l2))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }}
  ],
  right: [
    {{
      pattern: {json.dumps(parse(r1))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }},
    {{
      pattern: {json.dumps(parse(r2))},
      colors: ['transparent', '#1E90FF', '#FFDBAC', '#000000', '#FF0000', '#FFD700', '#FFFFFF', '#00008B']
    }}
  ]
}};"""

with open('new_sprites_32.js', 'w') as f:
    f.write(output)

print("Generated new_sprites_32.js")
